[package]
name = "rs-fsring"
version = "2.2.0"
edition = "2021"
description = "A ring(like) buffer using filesystem"
license = "Apache-2.0"
documentation = "https://docs.rs/crate/rs-fsring/latest"
repository = "https://github.com/takanoriyanagitani/rs-fsring"

[dependencies]
